### ISSUE TITLE
Identify JMRI?

### ISSUE THREAD

**Issue by dwightkelly** [atanisoft/Esp32OlcbNodeBrowser#2]
The browser shows "02.01.12.7f.40.f0 | SNIP not available" for the JMRI node connected via LCC Buffer-USB. 

Would it be possible to display basic info (Mfg, Mod, Hardware, Software) for a JMRI node?

**Comment by atanisoft** [comment]
https://github.com/openlcb/OpenLCB_Java/issues/167 tracks the issue of JMRI not responding to PIP, however since the node ID namespace is known it should be catching this and sending a SNIP request anyways. I'll check this and confirm if the response is being received/processed correctly from JMRI.

**Comment by atanisoft** [comment]
The SNIP data is requested but not received within 1500ms (it's closer to 1600ms) when JMRI is connected over WiFi to the NB. I'll be updating OpenMRNIDF to bump the SNIP time limit from 1500ms to 2000ms.
